base:
    seed: &seed 42
model:
    type: Llava
    path: /mnt/disk1/lct/save_weights/llava-1.5-7b-hf
    torch_dtype: auto
eval:
    eval_pos: [transformed]
    type: vqa
    name: [mme]
    download: False
    path: /mnt/disk2/lct/datasets/vlm/MME
    bs: 1
    inference_per_block: False
sparse:
    method: TokenReduction
    special:
        method: SparseVLM
save:
    save_trans: False
    save_fake: False
    save_path: /path/to/save/
